# Generated by Django 5.2.12 on 2026-04-03 12:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['doctor', 'is_active'], name='patient_doctor_active_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['doctor', '-created_at'], name='patient_doctor_created_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['name'], name='patient_name_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['doctor', '-visit_date'], name='visit_doctor_date_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['patient', '-visit_date'], name='visit_patient_date_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['visit_date'], name='visit_date_idx'),
        ),
        migrations.AddIndex(
            model_name='visitfile',
            index=models.Index(fields=['visit'], name='visitfile_visit_idx'),
        ),
        migrations.AddIndex(
            model_name='visitfile',
            index=models.Index(fields=['doctor'], name='visitfile_doctor_idx'),
        ),
    ]
