# Generated by Django 5.2.11 on 2026-04-03 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_patient_doctor_active_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='patient',
            name='patient_doctor_active_idx',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='address',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='blood_type',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='emergency_contact_phone',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='is_active',
        ),
    ]
