# Generated by Django 5.2.12 on 2026-04-03 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_remove_patient_patient_doctor_active_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitfile',
            name='link_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='visitfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='visit_files/'),
        ),
    ]
