# Generated by Django 5.2.11 on 2026-04-11 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_visitfile_link_url_alter_visitfile_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(db_index=True, max_length=200, unique=True)),
                ('category', models.CharField(choices=[('drug', 'Drug Name'), ('diagnosis', 'Diagnosis'), ('symptom', 'Symptom'), ('procedure', 'Procedure'), ('other', 'Other')], default='drug', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Medical Dictionary',
                'verbose_name_plural': 'Medical Dictionary',
            },
        ),
        migrations.CreateModel(
            name='TranscriptionCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wrong_word', models.CharField(db_index=True, max_length=200)),
                ('correct_word', models.CharField(max_length=200)),
                ('usage_count', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_corrections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-usage_count'],
                'unique_together': {('doctor', 'wrong_word')},
            },
        ),
    ]
