# Generated by Django 5.2.11 on 2026-04-18 03:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_medicaldictionary_transcriptioncorrection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['next_checkup_date'], name='visit_checkup_date_idx'),
        ),
        migrations.AddIndex(
            model_name='visit',
            index=models.Index(fields=['doctor', 'next_checkup_date'], name='visit_doctor_checkup_idx'),
        ),
    ]
